{
  "hash": "36191b5e28ac1c5699b6db1591b0f0cc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take home Exercise 3\"\nauthor: \"Yang Lu\"\ndate: \"15 May 2025\"\ndate-modified: \"last-modified\"\nformat: html\neditor: visual\nexecute: \n  eval: true  \n  echo: true  \n  warning: false \n  freeze: true \n---\n\n\n\n# VAST Challenge 2025-Mini-Challenge 3\n\nFor the exercise, our group will choose MC 3 as our main topic, the detail background referring to [VAST MC3](https://vast-challenge.github.io/2025/MC3.html)\n\n## 1.0 Background\n\n**Oceanus: From Fishing Nets to Tourism Tensions**\n\nOnce defined by its fishing traditions, Oceanus has transformed dramatically in the last decade. After a crackdown on illegal fishing, those involved redirected investments toward ocean tourism, creating community friction. When international star Sailor Shift announced plans to film locally, investigative journalist Clepper Jessen uncovered troubling connections around the temporary closure of Nemo Reef. His work exposed expedited approvals and secretive arrangements linking island officials, Sailor's team, influential local families, and conservationists The Green Guardians—suggesting a story of corruption hiding beneath paradise's surface.\n\n### **2.0 Overall Tasks**\n\nClepper has built a knowledge graph from two weeks of intercepted radio communications in Oceanus. Here are the key tasks to be analyzed:\n\n**Task 1: Temporal Communication Patterns**\n\n1.  Create visual analytics to identify daily patterns in communication timing and analyze how these patterns changed over the two-week observation period\n\n2.  Select a specific entity and determine who influences them based on these patterns\n\n**Task 2: Relationship Analysis**\n\n1.  Develop visualizations to explore connections between vessels and people\n\n2.  Identify closely associated groups\n\n3.  Determine predominant topics for each group (e.g., environmentalism, Sailor Shift, fishing/leisure vessels)\n\n**Task 3: Pseudonym Identification**\n\n1.  Expand visualizations to reveal who is using pseudonyms\n\n2.  Identify known pseudonyms (\"Boss\", \"The Lookout\") and discover additional ones\n\n3.  Account for pseudonyms potentially used by multiple entities\n\n4.  Demonstrate how these visualizations simplify entity identification\n\n5.  Explain how understanding pseudonyms changes interpretation of activities\n\n**Task 4: Nadia Conti Investigation**\n\n1.  Use visual analytics to provide evidence regarding possible illegal activity by Nadia Conti\n\n2.  Create a visual summary of Nadia's actions\n\n3.  Assess whether Clepper's suspicions are justified\n\nEach task builds on previous analysis to uncover the potential corruption surrounding the Nemo Reef closure and connections between officials, Sailor Shift's team, influential families, and The Green Guardians.\n\n## 3.0 Setting up\n\n### 3.1 Loading packages\n\n| Package | Description |\n|:-----------------------------------|:-----------------------------------|\n| jsonlite | JSON parsing and generation |\n| tidyverse | Core data-science suite (dplyr, ggplot2, etc.) |\n| SmartEDA | Automated exploratory data analysis |\n| tidygraph | Tidy tools for graph-data manipulation and analysis |\n| ggraph | Grammar-based graph/network visualization |\n| lubridate | Easy parsing and manipulation of dates/times |\n| dplyr | Grammar of data manipulation (filter, mutate, etc.) |\n| patchwork | Combine multiple ggplots into a unified layout |\n| purrr | Functional programming tools for lists and vectors |\n| scales | Scale functions for visualization (axis breaks, formatting) |\n| RColorBrewer | Color palettes for maps and plots |\n| plotly | Interactive web-based charts |\n| igraph | Network analysis and graph algorithms |\n| viridis | Color scales for scientific visualization (colorblind-friendly) |\n| forcats | Tools for working with categorical variables (factors) |\n| knitr | Dynamic report generation and literate programming |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  jsonlite,\n  tidyverse,\n  SmartEDA,\n  tidygraph,\n  ggraph,\n  lubridate,\n  dplyr,\n  patchwork,\n  purrr,\n  scales,\n  RColorBrewer,\n  plotly,\n  igraph,\n  viridis,\n  forcats,\n  knitr,\n  visNetwork,\n  htmltools)\n```\n:::\n\n\n\n### 3.2 Loading data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMC3_graph <- fromJSON(\"data/MC3_graph.json\")\nglimpse(MC3_graph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ directed  : logi TRUE\n $ multigraph: logi FALSE\n $ graph     :List of 4\n  ..$ mode        : chr \"static\"\n  ..$ edge_default: Named list()\n  ..$ node_default: Named list()\n  ..$ name        : chr \"VAST_MC3_Knowledge_Graph\"\n $ nodes     :'data.frame':\t1159 obs. of  31 variables:\n  ..$ type             : chr [1:1159] \"Entity\" \"Entity\" \"Entity\" \"Entity\" ...\n  ..$ label            : chr [1:1159] \"Sam\" \"Kelly\" \"Nadia Conti\" \"Elise\" ...\n  ..$ name             : chr [1:1159] \"Sam\" \"Kelly\" \"Nadia Conti\" \"Elise\" ...\n  ..$ sub_type         : chr [1:1159] \"Person\" \"Person\" \"Person\" \"Person\" ...\n  ..$ id               : chr [1:1159] \"Sam\" \"Kelly\" \"Nadia Conti\" \"Elise\" ...\n  ..$ timestamp        : chr [1:1159] NA NA NA NA ...\n  ..$ monitoring_type  : chr [1:1159] NA NA NA NA ...\n  ..$ findings         : chr [1:1159] NA NA NA NA ...\n  ..$ content          : chr [1:1159] NA NA NA NA ...\n  ..$ assessment_type  : chr [1:1159] NA NA NA NA ...\n  ..$ results          : chr [1:1159] NA NA NA NA ...\n  ..$ movement_type    : chr [1:1159] NA NA NA NA ...\n  ..$ destination      : chr [1:1159] NA NA NA NA ...\n  ..$ enforcement_type : chr [1:1159] NA NA NA NA ...\n  ..$ outcome          : chr [1:1159] NA NA NA NA ...\n  ..$ activity_type    : chr [1:1159] NA NA NA NA ...\n  ..$ participants     : int [1:1159] NA NA NA NA NA NA NA NA NA NA ...\n  ..$ thing_collected  :'data.frame':\t1159 obs. of  2 variables:\n  .. ..$ type: chr [1:1159] NA NA NA NA ...\n  .. ..$ name: chr [1:1159] NA NA NA NA ...\n  ..$ reference        : chr [1:1159] NA NA NA NA ...\n  ..$ date             : chr [1:1159] NA NA NA NA ...\n  ..$ time             : chr [1:1159] NA NA NA NA ...\n  ..$ friendship_type  : chr [1:1159] NA NA NA NA ...\n  ..$ permission_type  : chr [1:1159] NA NA NA NA ...\n  ..$ start_date       : chr [1:1159] NA NA NA NA ...\n  ..$ end_date         : chr [1:1159] NA NA NA NA ...\n  ..$ report_type      : chr [1:1159] NA NA NA NA ...\n  ..$ submission_date  : chr [1:1159] NA NA NA NA ...\n  ..$ jurisdiction_type: chr [1:1159] NA NA NA NA ...\n  ..$ authority_level  : chr [1:1159] NA NA NA NA ...\n  ..$ coordination_type: chr [1:1159] NA NA NA NA ...\n  ..$ operational_role : chr [1:1159] NA NA NA NA ...\n $ edges     :'data.frame':\t3226 obs. of  5 variables:\n  ..$ id         : chr [1:3226] \"2\" \"3\" \"5\" \"3013\" ...\n  ..$ is_inferred: logi [1:3226] TRUE FALSE TRUE TRUE TRUE TRUE ...\n  ..$ source     : chr [1:3226] \"Sam\" \"Sam\" \"Sam\" \"Sam\" ...\n  ..$ target     : chr [1:3226] \"Relationship_Suspicious_217\" \"Event_Communication_370\" \"Event_Assessment_600\" \"Relationship_Colleagues_430\" ...\n  ..$ type       : chr [1:3226] NA \"sent\" NA NA ...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nMC3_schema <- fromJSON(\"data/MC3_schema.json\") # didint load \nglimpse(MC3_schema)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 1\n $ schema:List of 2\n  ..$ nodes:List of 3\n  .. ..$ Entity      :List of 2\n  .. ..$ Event       :List of 2\n  .. ..$ Relationship:List of 2\n  ..$ edges:List of 3\n  .. ..$ description: chr \"Connections between nodes in the knowledge graph\"\n  .. ..$ is_inferred: chr \"bool\"\n  .. ..$ types      :'data.frame':\t6 obs. of  5 variables:\n```\n\n\n:::\n:::\n\n\n\n### 3.3 Examining the data structure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes_tbl <- as_tibble(MC3_graph$nodes)\nedges_tbl <- as_tibble(MC3_graph$edges)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(nodes_tbl, 10))\n```\n\n::: {.cell-output-display}\n\n\n|type   |label          |name           |sub_type |id             |timestamp |monitoring_type |findings |content |assessment_type |results |movement_type |destination |enforcement_type |outcome |activity_type | participants|thing_collected |reference |date |time |friendship_type |permission_type |start_date |end_date |report_type |submission_date |jurisdiction_type |authority_level |coordination_type |operational_role |\n|:------|:--------------|:--------------|:--------|:--------------|:---------|:---------------|:--------|:-------|:---------------|:-------|:-------------|:-----------|:----------------|:-------|:-------------|------------:|:---------------|:---------|:----|:----|:---------------|:---------------|:----------|:--------|:-----------|:---------------|:-----------------|:---------------|:-----------------|:----------------|\n|Entity |Sam            |Sam            |Person   |Sam            |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Kelly          |Kelly          |Person   |Kelly          |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Nadia Conti    |Nadia Conti    |Person   |Nadia Conti    |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Elise          |Elise          |Person   |Elise          |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Liam Thorne    |Liam Thorne    |Person   |Liam Thorne    |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Samantha Blake |Samantha Blake |Person   |Samantha Blake |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Davis          |Davis          |Person   |Davis          |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Rodriguez      |Rodriguez      |Person   |Rodriguez      |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Sailor Shift   |Sailor Shift   |Person   |Sailor Shift   |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n|Entity |Clepper Jensen |Clepper Jensen |Person   |Clepper Jensen |NA        |NA              |NA       |NA      |NA              |NA      |NA            |NA          |NA               |NA      |NA            |           NA|NA              |NA        |NA   |NA   |NA              |NA              |NA         |NA       |NA          |NA              |NA                |NA              |NA                |NA               |\n\n\n:::\n\n```{.r .cell-code}\nkable(head(edges_tbl, 10))\n```\n\n::: {.cell-output-display}\n\n\n|id   |is_inferred |source |target                      |type |\n|:----|:-----------|:------|:---------------------------|:----|\n|2    |TRUE        |Sam    |Relationship_Suspicious_217 |NA   |\n|3    |FALSE       |Sam    |Event_Communication_370     |sent |\n|5    |TRUE        |Sam    |Event_Assessment_600        |NA   |\n|3013 |TRUE        |Sam    |Relationship_Colleagues_430 |NA   |\n|NA   |TRUE        |Sam    |Relationship_Friends_272    |NA   |\n|NA   |TRUE        |Sam    |Relationship_Colleagues_215 |NA   |\n|NA   |TRUE        |Sam    |Relationship_Colleagues_431 |NA   |\n|8    |FALSE       |Kelly  |Event_Communication_3       |sent |\n|10   |FALSE       |Kelly  |Event_Communication_443     |sent |\n|NA   |TRUE        |Kelly  |Relationship_Friends_272    |NA   |\n\n\n:::\n:::\n\n\n\nafter slpit to nodes and edges, the data shouw 3226 edges and 1159 nodes\n\n## 4.Initial EDA\n\nIt is time for us to apply appropriate EDA methods to examine the data.\n\nIn the code chunk below, ExpCatViz() of SmartEDA package is used to reveal the frequency distribution of all categorical fields in nodes_tbl tibble dataframe.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nExpCatViz(data = nodes_tbl,\n          col = \"red\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[4]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[5]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[6]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-6.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[7]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-7.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[8]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-8.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[9]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-9.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[10]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-10.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[11]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-11.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[12]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-12.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[13]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-13.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[14]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-6-14.png){width=672}\n:::\n:::\n\n\n\nOn the other hands, code chunk below uses ExpCATViz() of SmartEDA package to reveal the frequency distribution of all categorical fields in mc3_edges tibble dataframe.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nExpCatViz(data=edges_tbl,\n          col=\"lightblue\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n## 5.0 Task 1-Clepper found that messages frequently came in at around the same time each day.\n\n### Task 1.1: Create visual analytics to identify daily patterns in communication timing \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=nodes_tbl,\n      aes(y=`type`))+\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=nodes_tbl,\n      aes(y=`sub_type`))+\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n**Generate Node Sub-Type Inventory**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract unique sub_types for each node type\nentities      <- sort(unique(nodes_tbl$sub_type[nodes_tbl$type == \"Entity\"]))\nevents        <- sort(unique(nodes_tbl$sub_type[nodes_tbl$type == \"Event\"]))\nrelationships <- sort(unique(nodes_tbl$sub_type[nodes_tbl$type == \"Relationship\"]))\n\nnode_inventory <- list(\n  Entities      = entities,\n  Events        = events,\n  Relationships = relationships\n)\n```\n:::\n\n\n\n**List down type and relevant sub types**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (grp in names(node_inventory)) {\n  cat(\"**\", grp, \"** (\", length(node_inventory[[grp]]), \"):\\n\", sep = \"\")\n  cat(paste0(\"  - \", node_inventory[[grp]]), sep = \"\\n\")\n  cat(\"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Entities** (5):\n  - Group\n  - Location\n  - Organization\n  - Person\n  - Vessel\n\n**Events** (11):\n  - Assessment\n  - Collaborate\n  - Communication\n  - Criticize\n  - Enforcement\n  - Fishing\n  - HarborReport\n  - Monitoring\n  - TourActivity\n  - TransponderPing\n  - VesselMovement\n\n**Relationships** (9):\n  - AccessPermission\n  - Colleagues\n  - Coordinates\n  - Friends\n  - Jurisdiction\n  - Operates\n  - Reports\n  - Suspicious\n  - Unfriendly\n```\n\n\n:::\n:::\n\n\n\nbased on the above list, we noticed that based on the task requirement, now we only focus on type=\"event\" and sub_type =\"communication\" , next step is to create communication nodes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomm_nodes <-nodes_tbl %>%\n  filter(type==\"Event\",\n         sub_type == \"Communication\") %>%\n  select(event_id = id,timestamp)\n\nglimpse(comm_nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 584\nColumns: 2\n$ event_id  <chr> \"Event_Communication_1\", \"Event_Communication_2\", \"Event_Com…\n$ timestamp <chr> \"2040-10-01 08:09:00\", \"2040-10-01 08:10:00\", \"2040-10-01 08…\n```\n\n\n:::\n:::\n\n\n\n**Define sender and receiver**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=edges_tbl,\n      aes(y=`type`))+\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n**extract data from sender and receiver**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsent_edges <-edges_tbl %>% filter(type==\"sent\")%>%\n  select(sender = source,event_id=target)\n\nrecv_edges <-edges_tbl %>% filter(type==\"received\")%>%\n  select(event_id = source,receiver=target)\n```\n:::\n\n\n\n**using inner_join to combine sender and receiver**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmsgs <- sent_edges %>%\n  inner_join(recv_edges, by=\"event_id\") %>%\n  inner_join(comm_nodes, by=\"event_id\") %>%\n  mutate(ts = ymd_hms(timestamp, tz=\"UTC\")) %>%\n  mutate(date = as_date(ts), hour = hour(ts))\n```\n:::\n\n\n\n**visualizing the heat map**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheatmap_data <- msgs %>%\n  count(date, hour) %>%\n  complete(\n    date = seq(min(date), max(date), by = \"1 day\"),\n    hour = 0:23,\n    fill = list(n = 0)\n  )\n\nggplot(heatmap_data, aes(x=hour, y=date, fill=n)) +\n  geom_tile(color=\"white\") +\n  scale_x_continuous(\n    breaks = 0:23,\n    expand = c(0,0)\n  )+\n  scale_y_date(\n    breaks = seq(min(heatmap_data$date), max(heatmap_data$date), by = \"1 day\"),\n    date_labels = \"%b %d\",\n    expand = c(0, 0)\n  ) +\n scale_fill_distiller(\n    name    = \"Messages\",\n    palette = \"Spectral\",\n    direction = 1\n  ) +\n  \n  labs(\n    title = \"Daily Communication Patterns\",\n    x     = \"Hour of Day\",\n    y     = \"Date\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x  = element_text(hjust = 0.5),\n    axis.text.y  = element_text(size = 8),\n    panel.grid  = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n### Task 1.2 Compare the shape of daily rhythm between week 1 and week 2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n # Mark Week 1 vs Week 2\nmsgs <- msgs %>%\n  mutate(\n    week = if_else(date <= min(date) + days(6), \"Week 1\", \"Week 2\")\n  )\n\n# Count and normalize within each week\nweek_patterns <- msgs %>%\n  count(week, hour) %>%\n  group_by(week) %>%\n  mutate(proportion = n / sum(n))\n\n\nhour_breaks <- seq(min(week_patterns$hour), max(week_patterns$hour), by = 1)\nprop_breaks <- seq(\n  0,\n  ceiling(max(week_patterns$proportion) * 100) / 100,\n  by = 0.02\n)\n\nggplot(week_patterns, aes(x = hour, y = proportion, color = week)) +\n  geom_line(size = 1.2) +\n  geom_point(size = 3) +\n  scale_x_continuous(breaks = hour_breaks) +\n  scale_y_continuous(\n    breaks = prop_breaks,\n    labels = percent_format(accuracy = 1)\n  ) +\n  labs(\n    title = \"Hourly Communication Patterns: Week 1 vs Week 2\",\n    x     = \"Hour of Day\",\n    y     = \"Percent of Total Messages\"\n  ) +\n  theme_light(base_size = 12) +\n  theme(\n    plot.title      = element_text(face = \"bold\", size = 16, hjust = 0.5),\n    legend.position = \"top\",\n    legend.title    = element_blank(),\n    panel.grid.major = element_line(color = \"grey80\"),\n    panel.grid.minor = element_line(color = \"grey90\"),\n    axis.text.x     = element_text(vjust = 0.5),\n    axis.text.y     = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n### Task 1.3: Focus on a specific entity and use this information to determine who has influence over them.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nentity_info <- nodes_tbl %>%\n  filter(type == \"Entity\") %>%\n  select(id, target_subtype = sub_type)\n\nmsgs2 <- msgs %>%\n  left_join(entity_info, by = c(\"receiver\" = \"id\"))\n\n\ntop_inf <- msgs2 %>%\n  filter(!is.na(receiver)) %>%\n  count(target_subtype, receiver, sender, sort = TRUE) %>%\n  group_by(target_subtype, receiver) %>%\n  slice_max(n, n = 10) %>%\n  ungroup()\n\nplot_list <- top_inf %>%\n  group_split(target_subtype) %>%\n  map(~{\n    subtype <- unique(.x$target_subtype)\n    ggplot(.x, aes(\n        x     = reorder(sender, n, .desc=TRUE),\n        y     = n,\n        fill  = receiver,\n        text  = paste0(\n          \"Subtype: \", subtype, \"<br>\",\n          \"Sender: \", sender, \"<br>\",\n          \"Receiver: \", receiver, \"<br>\",\n          \"Count: \", n\n        )\n      )) +\n      geom_col(color = \"white\") +                    \n      scale_fill_viridis_d(option = \"turbo\", name=\"Receiver\") +\n      coord_flip() +\n      labs(\n        title = paste(\"Subtype:\", subtype),\n        x     = \"Influencer (Sender)\",\n        y     = \"Message Count\"\n      ) +\n      theme_minimal(base_size = 12) +\n      theme(\n        strip.text       = element_text(face = \"bold\"),\n        axis.text.y      = element_text(size = 8),\n        panel.grid.major = element_line(color = \"grey80\"),\n        panel.grid.minor = element_line(color = \"grey90\"),\n        legend.position  = \"bottom\"\n      )\n  })\n\n\nplots <- map(plot_list, ~ggplotly(.x, tooltip = \"text\"))\ntagList(plots)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-6ab3ed63a909d862ac23\" style=\"width:100%;height:400px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6ab3ed63a909d862ac23\">{\"x\":{\"data\":[{\"orientation\":\"h\",\"width\":0.89999999999999991,\"base\":0,\"x\":[1],\"y\":[1],\"text\":\"Subtype: Group<br>Sender: Neptune<br>Receiver: City Officials<br>Count: 1\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(48,18,59,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"City Officials\",\"legendgroup\":\"City Officials\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.286425902864259,\"r\":7.9701120797011216,\"b\":43.835616438356169,\"l\":65.089248650892486},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Subtype: Group\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.050000000000000003,1.05],\"tickmode\":\"array\",\"ticktext\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"categoryorder\":\"array\",\"categoryarray\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Message Count\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,1.6000000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Neptune\"],\"tickvals\":[1],\"categoryorder\":\"array\",\"categoryarray\":[\"Neptune\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":10.62681610626816},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Influencer (Sender)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"Receiver\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"44981e7368db\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"44981e7368db\",\"visdat\":{\"44981e7368db\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-f201c79c39dd8aa2907e\" style=\"width:100%;height:400px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f201c79c39dd8aa2907e\">{\"x\":{\"data\":[{\"orientation\":\"h\",\"width\":[0.90000000000000036,0.90000000000000036],\"base\":[0,0],\"x\":[1,1],\"y\":[3,4],\"text\":[\"Subtype: Location<br>Sender: Knowles<br>Receiver: Haacklee Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: Nadia Conti<br>Receiver: Haacklee Harbor<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(48,18,59,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Haacklee Harbor\",\"legendgroup\":\"Haacklee Harbor\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999991,0.90000000000000036,0.90000000000000036,0.89999999999999858,0.90000000000000036],\"base\":[6,2,0,0,0,0,0,3,0],\"x\":[5,4,2,2,1,1,1,1,1],\"y\":[15,14,11,13,1,5,6,12,7],\"text\":[\"Subtype: Location<br>Sender: Oceanus City Council<br>Receiver: Himark Harbor<br>Count: 5\",\"Subtype: Location<br>Sender: Mako<br>Receiver: Himark Harbor<br>Count: 4\",\"Subtype: Location<br>Sender: Marlin<br>Receiver: Himark Harbor<br>Count: 2\",\"Subtype: Location<br>Sender: Serenity<br>Receiver: Himark Harbor<br>Count: 2\",\"Subtype: Location<br>Sender: Davis<br>Receiver: Himark Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: Neptune<br>Receiver: Himark Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: Northern Light<br>Receiver: Himark Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: Remora<br>Receiver: Himark Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: Seawatch<br>Receiver: Himark Harbor<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(26,228,182,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Himark Harbor\",\"legendgroup\":\"Himark Harbor\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000013,0.89999999999999947,0.89999999999999858],\"base\":[0,0,0,1,0,0,0],\"x\":[6,3,2,2,1,1,1],\"y\":[15,12,14,10,2,8,9],\"text\":[\"Subtype: Location<br>Sender: Oceanus City Council<br>Receiver: Paackland Harbor<br>Count: 6\",\"Subtype: Location<br>Sender: Remora<br>Receiver: Paackland Harbor<br>Count: 3\",\"Subtype: Location<br>Sender: Mako<br>Receiver: Paackland Harbor<br>Count: 2\",\"Subtype: Location<br>Sender: Reef Guardian<br>Receiver: Paackland Harbor<br>Count: 2\",\"Subtype: Location<br>Sender: Green Guardians<br>Receiver: Paackland Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: Sentinel<br>Receiver: Paackland Harbor<br>Count: 1\",\"Subtype: Location<br>Sender: The Middleman<br>Receiver: Paackland Harbor<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(250,186,57,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Paackland Harbor\",\"legendgroup\":\"Paackland Harbor\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.89999999999999858,\"base\":0,\"x\":[1],\"y\":[10],\"text\":\"Subtype: Location<br>Sender: Reef Guardian<br>Receiver: Port Security<br>Count: 1\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(122,4,3,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Port Security\",\"legendgroup\":\"Port Security\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.286425902864259,\"r\":7.9701120797011216,\"b\":43.835616438356169,\"l\":134.16355334163552},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Subtype: Location\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.55000000000000004,11.550000000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"3\",\"6\",\"9\"],\"tickvals\":[0,3,6.0000000000000009,9],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"3\",\"6\",\"9\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Message Count\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,15.6],\"tickmode\":\"array\",\"ticktext\":[\"Davis\",\"Green Guardians\",\"Knowles\",\"Nadia Conti\",\"Neptune\",\"Northern Light\",\"Seawatch\",\"Sentinel\",\"The Middleman\",\"Reef Guardian\",\"Marlin\",\"Remora\",\"Serenity\",\"Mako\",\"Oceanus City Council\"],\"tickvals\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],\"categoryorder\":\"array\",\"categoryarray\":[\"Davis\",\"Green Guardians\",\"Knowles\",\"Nadia Conti\",\"Neptune\",\"Northern Light\",\"Seawatch\",\"Sentinel\",\"The Middleman\",\"Reef Guardian\",\"Marlin\",\"Remora\",\"Serenity\",\"Mako\",\"Oceanus City Council\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":10.62681610626816},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Influencer (Sender)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"Receiver\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"44987be62a4e\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"44987be62a4e\",\"visdat\":{\"44987be62a4e\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-548e1fb55a18406c397b\" style=\"width:100%;height:400px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-548e1fb55a18406c397b\">{\"x\":{\"data\":[{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999947,0.89999999999999858],\"base\":[12,1,0,1,2,2,0],\"x\":[12,6,3,2,2,1,1],\"y\":[25,20,19,11,16,8,10],\"text\":[\"Subtype: Organization<br>Sender: Green Guardians<br>Receiver: Green Guardians<br>Count: 12\",\"Subtype: Organization<br>Sender: Oceanus City Council<br>Receiver: Green Guardians<br>Count: 6\",\"Subtype: Organization<br>Sender: The Lookout<br>Receiver: Green Guardians<br>Count: 3\",\"Subtype: Organization<br>Sender: Horizon<br>Receiver: Green Guardians<br>Count: 2\",\"Subtype: Organization<br>Sender: Sentinel<br>Receiver: Green Guardians<br>Count: 2\",\"Subtype: Organization<br>Sender: Northern Light<br>Receiver: Green Guardians<br>Count: 1\",\"Subtype: Organization<br>Sender: Seawatch<br>Receiver: Green Guardians<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(48,18,59,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Green Guardians\",\"legendgroup\":\"Green Guardians\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000013,0.89999999999999858,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.89999999999999947,0.89999999999999858],\"base\":[0,0,0,0,3,0,0,0,0,0,2,0,1,1,0],\"x\":[12,7,6,4,3,2,2,2,1,1,1,1,1,1,1],\"y\":[25,23,22,21,18,14,15,16,2,11,4,5,7,8,20],\"text\":[\"Subtype: Organization<br>Sender: Green Guardians<br>Receiver: Oceanus City Council<br>Count: 12\",\"Subtype: Organization<br>Sender: Himark Harbor<br>Receiver: Oceanus City Council<br>Count: 7\",\"Subtype: Organization<br>Sender: Liam Thorne<br>Receiver: Oceanus City Council<br>Count: 6\",\"Subtype: Organization<br>Sender: Reef Guardian<br>Receiver: Oceanus City Council<br>Count: 4\",\"Subtype: Organization<br>Sender: Samantha Blake<br>Receiver: Oceanus City Council<br>Count: 3\",\"Subtype: Organization<br>Sender: Haacklee Harbor<br>Receiver: Oceanus City Council<br>Count: 2\",\"Subtype: Organization<br>Sender: Paackland Harbor<br>Receiver: Oceanus City Council<br>Count: 2\",\"Subtype: Organization<br>Sender: Sentinel<br>Receiver: Oceanus City Council<br>Count: 2\",\"Subtype: Organization<br>Sender: EcoVigil<br>Receiver: Oceanus City Council<br>Count: 1\",\"Subtype: Organization<br>Sender: Horizon<br>Receiver: Oceanus City Council<br>Count: 1\",\"Subtype: Organization<br>Sender: Mako<br>Receiver: Oceanus City Council<br>Count: 1\",\"Subtype: Organization<br>Sender: Marlin<br>Receiver: Oceanus City Council<br>Count: 1\",\"Subtype: Organization<br>Sender: Nadia Conti<br>Receiver: Oceanus City Council<br>Count: 1\",\"Subtype: Organization<br>Sender: Northern Light<br>Receiver: Oceanus City Council<br>Count: 1\",\"Subtype: Organization<br>Sender: Oceanus City Council<br>Receiver: Oceanus City Council<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(26,228,182,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Oceanus City Council\",\"legendgroup\":\"Oceanus City Council\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.90000000000000036,0.89999999999999947,0.89999999999999858],\"base\":[0,1,1,0,0],\"x\":[3,2,1,1,1],\"y\":[18,12,4,8,9],\"text\":[\"Subtype: Organization<br>Sender: Samantha Blake<br>Receiver: Sailor Shifts Team<br>Count: 3\",\"Subtype: Organization<br>Sender: Remora<br>Receiver: Sailor Shifts Team<br>Count: 2\",\"Subtype: Organization<br>Sender: Mako<br>Receiver: Sailor Shifts Team<br>Count: 1\",\"Subtype: Organization<br>Sender: Northern Light<br>Receiver: Sailor Shifts Team<br>Count: 1\",\"Subtype: Organization<br>Sender: Rodriguez<br>Receiver: Sailor Shifts Team<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(250,186,57,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Sailor Shifts Team\",\"legendgroup\":\"Sailor Shifts Team\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999991,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.89999999999999858],\"base\":[0,0,0,0,0,0,0,0,0],\"x\":[8,2,2,1,1,1,1,1,1],\"y\":[24,13,17,1,3,4,6,7,12],\"text\":[\"Subtype: Organization<br>Sender: Neptune<br>Receiver: V. Miesel Shipping<br>Count: 8\",\"Subtype: Organization<br>Sender: Davis<br>Receiver: V. Miesel Shipping<br>Count: 2\",\"Subtype: Organization<br>Sender: V. Miesel Shipping<br>Receiver: V. Miesel Shipping<br>Count: 2\",\"Subtype: Organization<br>Sender: Boss<br>Receiver: V. Miesel Shipping<br>Count: 1\",\"Subtype: Organization<br>Sender: Elise<br>Receiver: V. Miesel Shipping<br>Count: 1\",\"Subtype: Organization<br>Sender: Mako<br>Receiver: V. Miesel Shipping<br>Count: 1\",\"Subtype: Organization<br>Sender: Mrs. Money<br>Receiver: V. Miesel Shipping<br>Count: 1\",\"Subtype: Organization<br>Sender: Nadia Conti<br>Receiver: V. Miesel Shipping<br>Count: 1\",\"Subtype: Organization<br>Sender: Remora<br>Receiver: V. Miesel Shipping<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(122,4,3,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"V. Miesel Shipping\",\"legendgroup\":\"V. Miesel Shipping\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.286425902864259,\"r\":7.9701120797011216,\"b\":43.835616438356169,\"l\":134.16355334163552},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Subtype: Organization\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1.2000000000000002,25.199999999999999],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"5\",\"10\",\"15\",\"20\",\"25\"],\"tickvals\":[0,5,10,15,20,25],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"5\",\"10\",\"15\",\"20\",\"25\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Message Count\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,25.600000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Boss\",\"EcoVigil\",\"Elise\",\"Mako\",\"Marlin\",\"Mrs. Money\",\"Nadia Conti\",\"Northern Light\",\"Rodriguez\",\"Seawatch\",\"Horizon\",\"Remora\",\"Davis\",\"Haacklee Harbor\",\"Paackland Harbor\",\"Sentinel\",\"V. Miesel Shipping\",\"Samantha Blake\",\"The Lookout\",\"Oceanus City Council\",\"Reef Guardian\",\"Liam Thorne\",\"Himark Harbor\",\"Neptune\",\"Green Guardians\"],\"tickvals\":[1,2,3,4,5,6,7,7.9999999999999991,9,10,11,12,13,14.000000000000002,15,16,17,18,19,20,21,22,23,24,25],\"categoryorder\":\"array\",\"categoryarray\":[\"Boss\",\"EcoVigil\",\"Elise\",\"Mako\",\"Marlin\",\"Mrs. Money\",\"Nadia Conti\",\"Northern Light\",\"Rodriguez\",\"Seawatch\",\"Horizon\",\"Remora\",\"Davis\",\"Haacklee Harbor\",\"Paackland Harbor\",\"Sentinel\",\"V. Miesel Shipping\",\"Samantha Blake\",\"The Lookout\",\"Oceanus City Council\",\"Reef Guardian\",\"Liam Thorne\",\"Himark Harbor\",\"Neptune\",\"Green Guardians\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":10.62681610626816},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Influencer (Sender)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"Receiver\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"449835811170\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"449835811170\",\"visdat\":{\"449835811170\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-2e69bc4c52692c306ea6\" style=\"width:100%;height:400px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-2e69bc4c52692c306ea6\">{\"x\":{\"data\":[{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999991,0.89999999999999858,0.89999999999999947],\"base\":[8,8,9,6,1,11,1,3,5],\"x\":[6,4,3,2,2,1,1,1,1],\"y\":[24,20,19,15,10,23,1,9,8],\"text\":[\"Subtype: Person<br>Sender: Mrs. Money<br>Receiver: Boss<br>Count: 6\",\"Subtype: Person<br>Sender: The Middleman<br>Receiver: Boss<br>Count: 4\",\"Subtype: Person<br>Sender: Rodriguez<br>Receiver: Boss<br>Count: 3\",\"Subtype: Person<br>Sender: Mako<br>Receiver: Boss<br>Count: 2\",\"Subtype: Person<br>Sender: The Accountant<br>Receiver: Boss<br>Count: 2\",\"Subtype: Person<br>Sender: Davis<br>Receiver: Boss<br>Count: 1\",\"Subtype: Person<br>Sender: Glitters Team<br>Receiver: Boss<br>Count: 1\",\"Subtype: Person<br>Sender: Liam Thorne<br>Receiver: Boss<br>Count: 1\",\"Subtype: Person<br>Sender: V. Miesel Shipping<br>Receiver: Boss<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(48,18,59,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Boss\",\"legendgroup\":\"Boss\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.89999999999999858,\"base\":0,\"x\":[18],\"y\":[27],\"text\":\"Subtype: Person<br>Sender: Miranda Jordan<br>Receiver: Clepper Jensen<br>Count: 18\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(65,67,167,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Clepper Jensen\",\"legendgroup\":\"Clepper Jensen\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000036,0.89999999999999947],\"base\":[5,6,0,4,0,5,2,4],\"x\":[6,3,2,2,2,1,1,1],\"y\":[23,19,14,17,18,15,4,8],\"text\":[\"Subtype: Person<br>Sender: Davis<br>Receiver: Davis<br>Count: 6\",\"Subtype: Person<br>Sender: Rodriguez<br>Receiver: Davis<br>Count: 3\",\"Subtype: Person<br>Sender: Knowles<br>Receiver: Davis<br>Count: 2\",\"Subtype: Person<br>Sender: Neptune<br>Receiver: Davis<br>Count: 2\",\"Subtype: Person<br>Sender: Small Fry<br>Receiver: Davis<br>Count: 2\",\"Subtype: Person<br>Sender: Mako<br>Receiver: Davis<br>Count: 1\",\"Subtype: Person<br>Sender: Remora<br>Receiver: Davis<br>Count: 1\",\"Subtype: Person<br>Sender: V. Miesel Shipping<br>Receiver: Davis<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(71,113,233,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Davis\",\"legendgroup\":\"Davis\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999947],\"base\":[1,2,4,3],\"x\":[3,1,1,1],\"y\":[17,9,15,8],\"text\":[\"Subtype: Person<br>Sender: Neptune<br>Receiver: Elise<br>Count: 3\",\"Subtype: Person<br>Sender: Liam Thorne<br>Receiver: Elise<br>Count: 1\",\"Subtype: Person<br>Sender: Mako<br>Receiver: Elise<br>Count: 1\",\"Subtype: Person<br>Sender: V. Miesel Shipping<br>Receiver: Elise<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(62,155,254,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Elise\",\"legendgroup\":\"Elise\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.90000000000000036,\"base\":0,\"x\":[1],\"y\":[6],\"text\":\"Subtype: Person<br>Sender: Sam<br>Receiver: Kelly<br>Count: 1\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(34,197,226,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Kelly\",\"legendgroup\":\"Kelly\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000036],\"base\":[3,0,0,6,3,0],\"x\":[8,2,2,2,1,1],\"y\":[22,11,16,20,12,3],\"text\":[\"Subtype: Person<br>Sender: Oceanus City Council<br>Receiver: Liam Thorne<br>Count: 8\",\"Subtype: Person<br>Sender: EcoVigil<br>Receiver: Liam Thorne<br>Count: 2\",\"Subtype: Person<br>Sender: Nadia Conti<br>Receiver: Liam Thorne<br>Count: 2\",\"Subtype: Person<br>Sender: The Middleman<br>Receiver: Liam Thorne<br>Count: 2\",\"Subtype: Person<br>Sender: Elise<br>Receiver: Liam Thorne<br>Count: 1\",\"Subtype: Person<br>Sender: Paackland Harbor<br>Receiver: Liam Thorne<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(26,228,182,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Liam Thorne\",\"legendgroup\":\"Liam Thorne\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.89999999999999858,\"base\":0,\"x\":[20],\"y\":[28],\"text\":\"Subtype: Person<br>Sender: Clepper Jensen<br>Receiver: Miranda Jordan<br>Count: 20\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(70,248,132,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Miranda Jordan\",\"legendgroup\":\"Miranda Jordan\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999947],\"base\":[9,3,3,5,2],\"x\":[15,4,3,1,1],\"y\":[25,21,20,19,8],\"text\":[\"Subtype: Person<br>Sender: The Intern<br>Receiver: Mrs. Money<br>Count: 15\",\"Subtype: Person<br>Sender: Boss<br>Receiver: Mrs. Money<br>Count: 4\",\"Subtype: Person<br>Sender: The Middleman<br>Receiver: Mrs. Money<br>Count: 3\",\"Subtype: Person<br>Sender: Rodriguez<br>Receiver: Mrs. Money<br>Count: 1\",\"Subtype: Person<br>Sender: V. Miesel Shipping<br>Receiver: Mrs. Money<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(136,255,78,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Mrs. Money\",\"legendgroup\":\"Mrs. Money\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000013,0.89999999999999858,0.89999999999999858,0.90000000000000036,0.89999999999999858,0.90000000000000036,0.90000000000000036,0.89999999999999947],\"base\":[0,0,0,0,0,2,1,4,0,0,1],\"x\":[5,3,2,1,1,1,1,1,1,1,1],\"y\":[23,12,9,2,17,22,4,19,5,7,8],\"text\":[\"Subtype: Person<br>Sender: Davis<br>Receiver: Nadia Conti<br>Count: 5\",\"Subtype: Person<br>Sender: Elise<br>Receiver: Nadia Conti<br>Count: 3\",\"Subtype: Person<br>Sender: Liam Thorne<br>Receiver: Nadia Conti<br>Count: 2\",\"Subtype: Person<br>Sender: Haacklee Harbor<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: Neptune<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: Oceanus City Council<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: Remora<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: Rodriguez<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: Sailor Shifts Team<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: Sentinel<br>Receiver: Nadia Conti<br>Count: 1\",\"Subtype: Person<br>Sender: V. Miesel Shipping<br>Receiver: Nadia Conti<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(185,246,53,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Nadia Conti\",\"legendgroup\":\"Nadia Conti\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.90000000000000036,0.89999999999999947],\"base\":[0,0,0],\"x\":[4,1,1],\"y\":[19,4,8],\"text\":[\"Subtype: Person<br>Sender: Rodriguez<br>Receiver: Rodriguez<br>Count: 4\",\"Subtype: Person<br>Sender: Remora<br>Receiver: Rodriguez<br>Count: 1\",\"Subtype: Person<br>Sender: V. Miesel Shipping<br>Receiver: Rodriguez<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(225,221,55,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Rodriguez\",\"legendgroup\":\"Rodriguez\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858],\"base\":[12,0],\"x\":[8,2],\"y\":[26,13],\"text\":[\"Subtype: Person<br>Sender: The Lookout<br>Receiver: Sam<br>Count: 8\",\"Subtype: Person<br>Sender: Kelly<br>Receiver: Sam<br>Count: 2\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(250,186,57,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Sam\",\"legendgroup\":\"Sam\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999991],\"base\":[0,0,0],\"x\":[4,2,1],\"y\":[15,22,1],\"text\":[\"Subtype: Person<br>Sender: Mako<br>Receiver: Samantha Blake<br>Count: 4\",\"Subtype: Person<br>Sender: Oceanus City Council<br>Receiver: Samantha Blake<br>Count: 2\",\"Subtype: Person<br>Sender: Glitters Team<br>Receiver: Samantha Blake<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(253,141,39,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Samantha Blake\",\"legendgroup\":\"Samantha Blake\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.89999999999999858,\"base\":0,\"x\":[3],\"y\":[20],\"text\":\"Subtype: Person<br>Sender: The Middleman<br>Receiver: The Accountant<br>Count: 3\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(240,91,18,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"The Accountant\",\"legendgroup\":\"The Accountant\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[0,3,8],\"x\":[12,5,1],\"y\":[26,24,25],\"text\":[\"Subtype: Person<br>Sender: The Lookout<br>Receiver: The Intern<br>Count: 12\",\"Subtype: Person<br>Sender: Mrs. Money<br>Receiver: The Intern<br>Count: 5\",\"Subtype: Person<br>Sender: The Intern<br>Receiver: The Intern<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(214,53,6,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"The Intern\",\"legendgroup\":\"The Intern\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.89999999999999858,\"base\":0,\"x\":[8],\"y\":[25],\"text\":\"Subtype: Person<br>Sender: The Intern<br>Receiver: The Lookout<br>Count: 8\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(175,24,1,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"The Lookout\",\"legendgroup\":\"The Lookout\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[0,0,0],\"x\":[3,3,1],\"y\":[21,24,10],\"text\":[\"Subtype: Person<br>Sender: Boss<br>Receiver: The Middleman<br>Count: 3\",\"Subtype: Person<br>Sender: Mrs. Money<br>Receiver: The Middleman<br>Count: 3\",\"Subtype: Person<br>Sender: The Accountant<br>Receiver: The Middleman<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(122,4,3,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"The Middleman\",\"legendgroup\":\"The Middleman\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.286425902864259,\"r\":7.9701120797011216,\"b\":43.835616438356169,\"l\":134.16355334163552},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Subtype: Person\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1.2000000000000002,25.199999999999999],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"5\",\"10\",\"15\",\"20\",\"25\"],\"tickvals\":[0,5,10,15,20,25],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"5\",\"10\",\"15\",\"20\",\"25\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Message Count\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,28.600000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Glitters Team\",\"Haacklee Harbor\",\"Paackland Harbor\",\"Remora\",\"Sailor Shifts Team\",\"Sam\",\"Sentinel\",\"V. Miesel Shipping\",\"Liam Thorne\",\"The Accountant\",\"EcoVigil\",\"Elise\",\"Kelly\",\"Knowles\",\"Mako\",\"Nadia Conti\",\"Neptune\",\"Small Fry\",\"Rodriguez\",\"The Middleman\",\"Boss\",\"Oceanus City Council\",\"Davis\",\"Mrs. Money\",\"The Intern\",\"The Lookout\",\"Miranda Jordan\",\"Clepper Jensen\"],\"tickvals\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15.000000000000002,16,17,18,19,20,21,22,23,24,25,26,27,28],\"categoryorder\":\"array\",\"categoryarray\":[\"Glitters Team\",\"Haacklee Harbor\",\"Paackland Harbor\",\"Remora\",\"Sailor Shifts Team\",\"Sam\",\"Sentinel\",\"V. Miesel Shipping\",\"Liam Thorne\",\"The Accountant\",\"EcoVigil\",\"Elise\",\"Kelly\",\"Knowles\",\"Mako\",\"Nadia Conti\",\"Neptune\",\"Small Fry\",\"Rodriguez\",\"The Middleman\",\"Boss\",\"Oceanus City Council\",\"Davis\",\"Mrs. Money\",\"The Intern\",\"The Lookout\",\"Miranda Jordan\",\"Clepper Jensen\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":10.62681610626816},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Influencer (Sender)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"Receiver\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"44983c20614a\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"44983c20614a\",\"visdat\":{\"44983c20614a\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-4296034179e230ca53b6\" style=\"width:100%;height:400px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-4296034179e230ca53b6\">{\"x\":{\"data\":[{\"orientation\":\"h\",\"width\":0.89999999999999858,\"base\":25,\"x\":[2],\"y\":[15],\"text\":\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Defender<br>Count: 2\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(48,18,59,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Defender\",\"legendgroup\":\"Defender\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000013,0.90000000000000036,0.90000000000000036],\"base\":[21,16,7,9,2,0,7],\"x\":[4,3,3,2,1,1,1],\"y\":[15,16,13,17,2,3,7],\"text\":[\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: EcoVigil<br>Count: 4\",\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: EcoVigil<br>Count: 3\",\"Subtype: Vessel<br>Sender: Horizon<br>Receiver: EcoVigil<br>Count: 3\",\"Subtype: Vessel<br>Sender: EcoVigil<br>Receiver: EcoVigil<br>Count: 2\",\"Subtype: Vessel<br>Sender: Haacklee Harbor<br>Receiver: EcoVigil<br>Count: 1\",\"Subtype: Vessel<br>Sender: Liam Thorne<br>Receiver: EcoVigil<br>Count: 1\",\"Subtype: Vessel<br>Sender: Oceanus City Council<br>Receiver: EcoVigil<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(66,74,179,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"EcoVigil\",\"legendgroup\":\"EcoVigil\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[4,7,5,12,18],\"x\":[5,5,5,4,3],\"y\":[17,20,24,16,15],\"text\":[\"Subtype: Vessel<br>Sender: EcoVigil<br>Receiver: Horizon<br>Count: 5\",\"Subtype: Vessel<br>Sender: Sentinel<br>Receiver: Horizon<br>Count: 5\",\"Subtype: Vessel<br>Sender: The Lookout<br>Receiver: Horizon<br>Count: 5\",\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: Horizon<br>Count: 4\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Horizon<br>Count: 3\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(70,126,244,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Horizon\",\"legendgroup\":\"Horizon\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":0.90000000000000013,\"base\":1,\"x\":[1],\"y\":[2],\"text\":\"Subtype: Vessel<br>Sender: Haacklee Harbor<br>Receiver: Knowles<br>Count: 1\",\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(49,175,245,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Knowles\",\"legendgroup\":\"Knowles\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000036,0.89999999999999858,0.89999999999999858],\"base\":[6,11,0,5,2,17,10,0,10,5,16,4],\"x\":[9,7,6,5,5,3,3,3,2,2,2,2],\"y\":[28,26,27,23,20,18,22,19,16,7,15,12],\"text\":[\"Subtype: Vessel<br>Sender: Remora<br>Receiver: Mako<br>Count: 9\",\"Subtype: Vessel<br>Sender: Neptune<br>Receiver: Mako<br>Count: 7\",\"Subtype: Vessel<br>Sender: Osprey<br>Receiver: Mako<br>Count: 6\",\"Subtype: Vessel<br>Sender: Davis<br>Receiver: Mako<br>Count: 5\",\"Subtype: Vessel<br>Sender: Sentinel<br>Receiver: Mako<br>Count: 5\",\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Mako<br>Count: 3\",\"Subtype: Vessel<br>Sender: Paackland Harbor<br>Receiver: Mako<br>Count: 3\",\"Subtype: Vessel<br>Sender: Samantha Blake<br>Receiver: Mako<br>Count: 3\",\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: Mako<br>Count: 2\",\"Subtype: Vessel<br>Sender: Oceanus City Council<br>Receiver: Mako<br>Count: 2\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Mako<br>Count: 2\",\"Subtype: Vessel<br>Sender: Serenity<br>Receiver: Mako<br>Count: 2\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(24,218,199,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Mako\",\"legendgroup\":\"Mako\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000036],\"base\":[13,15,17,2,4],\"x\":[3,2,1,1,1],\"y\":[15,18,14,10,7],\"text\":[\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Marlin<br>Count: 3\",\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Marlin<br>Count: 2\",\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Marlin<br>Count: 1\",\"Subtype: Vessel<br>Sender: Nadia Conti<br>Receiver: Marlin<br>Count: 1\",\"Subtype: Vessel<br>Sender: Oceanus City Council<br>Receiver: Marlin<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(56,244,145,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Marlin\",\"legendgroup\":\"Marlin\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[0,10,2,14,1,0,2,4,12],\"x\":[6,5,4,3,2,2,2,1,1],\"y\":[28,18,21,14,9,10,12,23,15],\"text\":[\"Subtype: Vessel<br>Sender: Remora<br>Receiver: Neptune<br>Count: 6\",\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Neptune<br>Count: 5\",\"Subtype: Vessel<br>Sender: V. Miesel Shipping<br>Receiver: Neptune<br>Count: 4\",\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Neptune<br>Count: 3\",\"Subtype: Vessel<br>Sender: Mrs. Money<br>Receiver: Neptune<br>Count: 2\",\"Subtype: Vessel<br>Sender: Nadia Conti<br>Receiver: Neptune<br>Count: 2\",\"Subtype: Vessel<br>Sender: Serenity<br>Receiver: Neptune<br>Count: 2\",\"Subtype: Vessel<br>Sender: Davis<br>Receiver: Neptune<br>Count: 1\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Neptune<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(131,255,82,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Neptune\",\"legendgroup\":\"Neptune\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999991,0.89999999999999858,0.89999999999999858,0.90000000000000036],\"base\":[1,9,9,3],\"x\":[1,1,1,1],\"y\":[1,16,18,7],\"text\":[\"Subtype: Vessel<br>Sender: Glitters Team<br>Receiver: Northern Light<br>Count: 1\",\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: Northern Light<br>Count: 1\",\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Northern Light<br>Count: 1\",\"Subtype: Vessel<br>Sender: Oceanus City Council<br>Receiver: Northern Light<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(189,245,52,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Northern Light\",\"legendgroup\":\"Northern Light\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.90000000000000013],\"base\":[12,0],\"x\":[2,1],\"y\":[14,2],\"text\":[\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Osprey<br>Count: 2\",\"Subtype: Vessel<br>Sender: Haacklee Harbor<br>Receiver: Osprey<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(233,213,57,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Osprey\",\"legendgroup\":\"Osprey\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000036,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999947,0.89999999999999858,0.90000000000000036,0.89999999999999858,0.89999999999999858],\"base\":[3,1,9,2,10,1,8,0,6,2,10,0,1,4],\"x\":[6,3,3,2,2,2,2,2,1,1,1,1,1,1],\"y\":[16,11,15,17,14,7,22,12,13,8,26,6,20,24],\"text\":[\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: Reef Guardian<br>Count: 6\",\"Subtype: Vessel<br>Sender: Defender<br>Receiver: Reef Guardian<br>Count: 3\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Reef Guardian<br>Count: 3\",\"Subtype: Vessel<br>Sender: EcoVigil<br>Receiver: Reef Guardian<br>Count: 2\",\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Reef Guardian<br>Count: 2\",\"Subtype: Vessel<br>Sender: Oceanus City Council<br>Receiver: Reef Guardian<br>Count: 2\",\"Subtype: Vessel<br>Sender: Paackland Harbor<br>Receiver: Reef Guardian<br>Count: 2\",\"Subtype: Vessel<br>Sender: Serenity<br>Receiver: Reef Guardian<br>Count: 2\",\"Subtype: Vessel<br>Sender: Horizon<br>Receiver: Reef Guardian<br>Count: 1\",\"Subtype: Vessel<br>Sender: Marlin<br>Receiver: Reef Guardian<br>Count: 1\",\"Subtype: Vessel<br>Sender: Neptune<br>Receiver: Reef Guardian<br>Count: 1\",\"Subtype: Vessel<br>Sender: Seawatch<br>Receiver: Reef Guardian<br>Count: 1\",\"Subtype: Vessel<br>Sender: Sentinel<br>Receiver: Reef Guardian<br>Count: 1\",\"Subtype: Vessel<br>Sender: The Lookout<br>Receiver: Reef Guardian<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(254,170,51,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Reef Guardian\",\"legendgroup\":\"Reef Guardian\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999947,0.89999999999999858,0.89999999999999991,0.89999999999999858,0.90000000000000036,0.90000000000000036],\"base\":[1,5,0,4,0,6,0,0,0,0,0,0],\"x\":[9,5,4,4,4,3,2,2,1,1,1,1],\"y\":[26,14,23,22,25,18,8,21,1,9,4,5],\"text\":[\"Subtype: Vessel<br>Sender: Neptune<br>Receiver: Remora<br>Count: 9\",\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Remora<br>Count: 5\",\"Subtype: Vessel<br>Sender: Davis<br>Receiver: Remora<br>Count: 4\",\"Subtype: Vessel<br>Sender: Paackland Harbor<br>Receiver: Remora<br>Count: 4\",\"Subtype: Vessel<br>Sender: Small Fry<br>Receiver: Remora<br>Count: 4\",\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Remora<br>Count: 3\",\"Subtype: Vessel<br>Sender: Marlin<br>Receiver: Remora<br>Count: 2\",\"Subtype: Vessel<br>Sender: V. Miesel Shipping<br>Receiver: Remora<br>Count: 2\",\"Subtype: Vessel<br>Sender: Glitters Team<br>Receiver: Remora<br>Count: 1\",\"Subtype: Vessel<br>Sender: Mrs. Money<br>Receiver: Remora<br>Count: 1\",\"Subtype: Vessel<br>Sender: Rodriguez<br>Receiver: Remora<br>Count: 1\",\"Subtype: Vessel<br>Sender: Sailor Shifts Team<br>Receiver: Remora<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,114,28,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Remora\",\"legendgroup\":\"Remora\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[3,6,1,4,0,0],\"x\":[3,3,2,2,1,1],\"y\":[18,15,16,13,11,20],\"text\":[\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Seawatch<br>Count: 3\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Seawatch<br>Count: 3\",\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: Seawatch<br>Count: 2\",\"Subtype: Vessel<br>Sender: Horizon<br>Receiver: Seawatch<br>Count: 2\",\"Subtype: Vessel<br>Sender: Defender<br>Receiver: Seawatch<br>Count: 1\",\"Subtype: Vessel<br>Sender: Sentinel<br>Receiver: Seawatch<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(224,63,8,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Seawatch\",\"legendgroup\":\"Seawatch\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858,0.90000000000000036],\"base\":[0,1,0,0,3,0,0,0],\"x\":[4,4,4,4,3,2,1,1],\"y\":[13,14,22,24,15,17,16,7],\"text\":[\"Subtype: Vessel<br>Sender: Horizon<br>Receiver: Sentinel<br>Count: 4\",\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Sentinel<br>Count: 4\",\"Subtype: Vessel<br>Sender: Paackland Harbor<br>Receiver: Sentinel<br>Count: 4\",\"Subtype: Vessel<br>Sender: The Lookout<br>Receiver: Sentinel<br>Count: 4\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Sentinel<br>Count: 3\",\"Subtype: Vessel<br>Sender: EcoVigil<br>Receiver: Sentinel<br>Count: 2\",\"Subtype: Vessel<br>Sender: Green Guardians<br>Receiver: Sentinel<br>Count: 1\",\"Subtype: Vessel<br>Sender: Oceanus City Council<br>Receiver: Sentinel<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(182,28,2,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Sentinel\",\"legendgroup\":\"Sentinel\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"h\",\"width\":[0.89999999999999858,0.89999999999999858,0.89999999999999858,0.89999999999999858],\"base\":[0,0,0,0],\"x\":[3,3,1,1],\"y\":[18,15,14,26],\"text\":[\"Subtype: Vessel<br>Sender: Himark Harbor<br>Receiver: Serenity<br>Count: 3\",\"Subtype: Vessel<br>Sender: Reef Guardian<br>Receiver: Serenity<br>Count: 3\",\"Subtype: Vessel<br>Sender: Mako<br>Receiver: Serenity<br>Count: 1\",\"Subtype: Vessel<br>Sender: Neptune<br>Receiver: Serenity<br>Count: 1\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(122,4,3,1)\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(255,255,255,1)\"}},\"name\":\"Serenity\",\"legendgroup\":\"Serenity\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.286425902864259,\"r\":7.9701120797011216,\"b\":43.835616438356169,\"l\":134.16355334163552},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243},\"title\":{\"text\":\"Subtype: Vessel\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.128268991282692},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1.3500000000000001,28.350000000000001],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\"],\"tickvals\":[0,10,20],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":12.7521793275218},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Message Count\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,28.600000000000001],\"tickmode\":\"array\",\"ticktext\":[\"Glitters Team\",\"Haacklee Harbor\",\"Liam Thorne\",\"Rodriguez\",\"Sailor Shifts Team\",\"Seawatch\",\"Oceanus City Council\",\"Marlin\",\"Mrs. Money\",\"Nadia Conti\",\"Defender\",\"Serenity\",\"Horizon\",\"Mako\",\"Reef Guardian\",\"Green Guardians\",\"EcoVigil\",\"Himark Harbor\",\"Samantha Blake\",\"Sentinel\",\"V. Miesel Shipping\",\"Paackland Harbor\",\"Davis\",\"The Lookout\",\"Small Fry\",\"Neptune\",\"Osprey\",\"Remora\"],\"tickvals\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15.000000000000002,16,17,18,19,20,21,22,23,24,25,26,27,28],\"categoryorder\":\"array\",\"categoryarray\":[\"Glitters Team\",\"Haacklee Harbor\",\"Liam Thorne\",\"Rodriguez\",\"Sailor Shifts Team\",\"Seawatch\",\"Oceanus City Council\",\"Marlin\",\"Mrs. Money\",\"Nadia Conti\",\"Defender\",\"Serenity\",\"Horizon\",\"Mako\",\"Reef Guardian\",\"Green Guardians\",\"EcoVigil\",\"Himark Harbor\",\"Samantha Blake\",\"Sentinel\",\"V. Miesel Shipping\",\"Paackland Harbor\",\"Davis\",\"The Lookout\",\"Small Fry\",\"Neptune\",\"Osprey\",\"Remora\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.9850560398505608,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":10.62681610626816},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(204,204,204,1)\",\"gridwidth\":0.72455564360919278,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Influencer (Sender)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"Receiver\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.940224159402243}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"44985eb34bfc\":{\"x\":{},\"y\":{},\"fill\":{},\"text\":{},\"type\":\"bar\"}},\"cur_data\":\"44985eb34bfc\",\"visdat\":{\"44985eb34bfc\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: panel-tabset\n### Subtype:Group\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee_edges <- msgs %>% select(from = sender, to = receiver)\nentity_nodes <- nodes_tbl %>%\n  filter(type == \"Entity\") %>%\n  select(id, name)\n\nentity_graph <- tbl_graph(nodes = entity_nodes, edges = ee_edges, directed = TRUE)\n\n\ntarget <- \"Neptune\"\n\n\ng_ig <- as.igraph(entity_graph, strict = FALSE)\n\n\nroot_idx <- which(V(g_ig)$name == target)\n\n\nego_vs <- unique(c(\n  root_idx,\n  neighbors(g_ig, root_idx, mode = \"in\"),\n  neighbors(g_ig, root_idx, mode = \"out\")\n))\n\n\nsubg <- induced_subgraph(g_ig, vids = ego_vs)\n\n\nego_graph <- as_tbl_graph(subg)\n\n\nggraph(ego_graph, layout = \"kk\") +\n  geom_edge_link(\n    aes(label = NULL),\n    arrow = arrow(length = unit(4, \"mm\")),\n    end_cap = circle(3, 'mm'),\n    color = \"grey70\"\n  ) +\n  geom_node_point(\n    aes(filter = (name == target)),\n    size  = 6,\n    color = \"firebrick\"\n  ) +\n  geom_node_point(\n    aes(filter = (name != target)),\n    size  = 4,\n    color = \"steelblue\"\n  ) +\n  geom_node_text(aes(label = name), repel = TRUE, size = 3) +\n  labs(title = paste(\"Influence Network of\", target)) +\n  theme_graph()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n### Subtype: Location\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee_edges <- msgs %>% select(from = sender, to = receiver)\nentity_nodes <- nodes_tbl %>%\n  filter(type == \"Entity\") %>%\n  select(id, name)\n\nentity_graph <- tbl_graph(nodes = entity_nodes, edges = ee_edges, directed = TRUE)\n\n\ntarget <- \"Oceanus City Council\"\n\n\ng_ig <- as.igraph(entity_graph, strict = FALSE)\n\n\nroot_idx <- which(V(g_ig)$name == target)\n\n\nego_vs <- unique(c(\n  root_idx,\n  neighbors(g_ig, root_idx, mode = \"in\"),\n  neighbors(g_ig, root_idx, mode = \"out\")\n))\n\n\nsubg <- induced_subgraph(g_ig, vids = ego_vs)\n\n\nego_graph <- as_tbl_graph(subg)\n\n\nggraph(ego_graph, layout = \"kk\") +\n  geom_edge_link(\n    aes(label = NULL),\n    arrow = arrow(length = unit(4, \"mm\")),\n    end_cap = circle(3, 'mm'),\n    color = \"grey70\"\n  ) +\n  geom_node_point(\n    aes(filter = (name == target)),\n    size  = 6,\n    color = \"firebrick\"\n  ) +\n  geom_node_point(\n    aes(filter = (name != target)),\n    size  = 4,\n    color = \"steelblue\"\n  ) +\n  geom_node_text(aes(label = name), repel = TRUE, size = 3) +\n  labs(title = paste(\"Influence Network of\", target)) +\n  theme_graph()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n### Subtype:Organization\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee_edges <- msgs %>% select(from = sender, to = receiver)\nentity_nodes <- nodes_tbl %>%\n  filter(type == \"Entity\") %>%\n  select(id, name)\n\nentity_graph <- tbl_graph(nodes = entity_nodes, edges = ee_edges, directed = TRUE)\n\n\ntarget <- \"Green Guardians\"\n\n\ng_ig <- as.igraph(entity_graph, strict = FALSE)\n\n\nroot_idx <- which(V(g_ig)$name == target)\n\n\nego_vs <- unique(c(\n  root_idx,\n  neighbors(g_ig, root_idx, mode = \"in\"),\n  neighbors(g_ig, root_idx, mode = \"out\")\n))\n\n\nsubg <- induced_subgraph(g_ig, vids = ego_vs)\n\n\nego_graph <- as_tbl_graph(subg)\n\n\nggraph(ego_graph, layout = \"kk\") +\n  geom_edge_link(\n    aes(label = NULL),\n    arrow = arrow(length = unit(4, \"mm\")),\n    end_cap = circle(3, 'mm'),\n    color = \"grey70\"\n  ) +\n  geom_node_point(\n    aes(filter = (name == target)),\n    size  = 6,\n    color = \"firebrick\"\n  ) +\n  geom_node_point(\n    aes(filter = (name != target)),\n    size  = 4,\n    color = \"steelblue\"\n  ) +\n  geom_node_text(aes(label = name), repel = TRUE, size = 3) +\n  labs(title = paste(\"Influence Network of\", target)) +\n  theme_graph()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n### Subtype:Person\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee_edges <- msgs %>% select(from = sender, to = receiver)\nentity_nodes <- nodes_tbl %>%\n  filter(type == \"Entity\") %>%\n  select(id, name)\n\nentity_graph <- tbl_graph(nodes = entity_nodes, edges = ee_edges, directed = TRUE)\n\n\ntarget <- \"The Intern\"\n\n\ng_ig <- as.igraph(entity_graph, strict = FALSE)\n\n\nroot_idx <- which(V(g_ig)$name == target)\n\n\nego_vs <- unique(c(\n  root_idx,\n  neighbors(g_ig, root_idx, mode = \"in\"),\n  neighbors(g_ig, root_idx, mode = \"out\")\n))\n\n\nsubg <- induced_subgraph(g_ig, vids = ego_vs)\n\n\nego_graph <- as_tbl_graph(subg)\n\n\nggraph(ego_graph, layout = \"kk\") +\n  geom_edge_link(\n    aes(label = NULL),\n    arrow = arrow(length = unit(4, \"mm\")),\n    end_cap = circle(3, 'mm'),\n    color = \"grey70\"\n  ) +\n  geom_node_point(\n    aes(filter = (name == target)),\n    size  = 6,\n    color = \"firebrick\"\n  ) +\n  geom_node_point(\n    aes(filter = (name != target)),\n    size  = 4,\n    color = \"steelblue\"\n  ) +\n  geom_node_text(aes(label = name), repel = TRUE, size = 3) +\n  labs(title = paste(\"Influence Network of\", target)) +\n  theme_graph()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n### Vessel\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee_edges <- msgs %>% select(from = sender, to = receiver)\nentity_nodes <- nodes_tbl %>%\n  filter(type == \"Entity\") %>%\n  select(id, name)\n\nentity_graph <- tbl_graph(nodes = entity_nodes, edges = ee_edges, directed = TRUE)\n\n\ntarget <- \"Reef Guardian\"\n\n\ng_ig <- as.igraph(entity_graph, strict = FALSE)\n\n\nroot_idx <- which(V(g_ig)$name == target)\n\n\nego_vs <- unique(c(\n  root_idx,\n  neighbors(g_ig, root_idx, mode = \"in\"),\n  neighbors(g_ig, root_idx, mode = \"out\")\n))\n\n\nsubg <- induced_subgraph(g_ig, vids = ego_vs)\n\n\nego_graph <- as_tbl_graph(subg)\n\n\nggraph(ego_graph, layout = \"kk\") +\n  geom_edge_link(\n    aes(label = NULL),\n    arrow = arrow(length = unit(4, \"mm\")),\n    end_cap = circle(3, 'mm'),\n    color = \"grey70\"\n  ) +\n  geom_node_point(\n    aes(filter = (name == target)),\n    size  = 6,\n    color = \"firebrick\"\n  ) +\n  geom_node_point(\n    aes(filter = (name != target)),\n    size  = 4,\n    color = \"steelblue\"\n  ) +\n  geom_node_text(aes(label = name), repel = TRUE, size = 3) +\n  labs(title = paste(\"Influence Network of\", target)) +\n  theme_graph()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n:::\n\n## Task 2: Clepper has noticed that people often communicate with (or about) the same people or vessels, and that grouping them together may help with the investigation.\n\n### Task 2.1 :Develop visualizations to explore connections between vessels and people\n\nbased on the request, now we have to filter people and vessel\n\n#### Step1:Clean the nodes and edges data\n\nclean the raw nodes and edges data to ensure there are no missing values, all IDs are unique, and types are consistent.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmc3_nodes_cleaned <- nodes_tbl %>%\n  mutate(id = as.character(id)) %>%\n  filter(!is.na(id)) %>%\n  distinct(id, .keep_all = TRUE) %>%\n  select(-thing_collected)\n\nmc3_edges_cleaned <- edges_tbl %>%\n  rename(from_id = source, to_id = target) %>%\n  mutate(across(c(from_id, to_id), as.character)) %>%\n  filter(from_id %in% mc3_nodes_cleaned$id, to_id %in% mc3_nodes_cleaned$id) %>%\n  filter(!is.na(from_id), !is.na(to_id))\n```\n:::\n\n\n\n#### Step 2: Extract person–vessel indirect links\n\nIdentify \"Person\" and \"Vessel\" nodes, and link them through \"Relationship\" nodes to extract all person–relationship–vessel triples.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeople_nodes <- mc3_nodes_cleaned %>% filter(sub_type == \"Person\")\nvessel_nodes <- mc3_nodes_cleaned %>% filter(sub_type == \"Vessel\")\n\nperson_relationship_edges <- mc3_edges_cleaned %>%\n  filter(from_id %in% people_nodes$id & grepl(\"^Relationship_\", to_id))\n\nrelationship_vessel_edges <- mc3_edges_cleaned %>%\n  filter(grepl(\"^Relationship_\", from_id) & to_id %in% vessel_nodes$id)\n\nperson_to_relationship <- person_relationship_edges %>%\n  select(person_id = from_id, relationship_id = to_id)\nrelationship_to_vessel <- relationship_vessel_edges %>%\n  select(relationship_id = from_id, vessel_id = to_id)\n\nperson_vessel_links <- person_to_relationship %>%\n  inner_join(relationship_to_vessel, by = \"relationship_id\") %>%\n  select(person_id, vessel_id, relationship_id)\n```\n:::\n\n\n\n#### Step 3: Add labels and types for nodes and edges \n\nAdd labels to each person and vessel node, and add relationship type to edges for visualization.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperson_vessel_links <- person_vessel_links %>%\n  left_join(people_nodes %>% select(id, person_label = label), by = c(\"person_id\" = \"id\")) %>%\n  left_join(vessel_nodes %>% select(id, vessel_label = label), by = c(\"vessel_id\" = \"id\"))\n\nedges_pv <- person_vessel_links %>%\n  mutate(\n    from = person_label,\n    to = vessel_label,\n    relationship_type = gsub(\"Relationship_|_[0-9]+\", \"\", relationship_id)\n  ) %>%\n  select(from, to, relationship_type)\n```\n:::\n\n\n\n#### Step 4: Prepare nodes/edges table for visualization \n\nCombine all nodes (person + vessel) into a nodes dataframe with type and color, and add color to the edge dataframe.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes <- data.frame(\n  id = unique(c(edges_pv$from, edges_pv$to)),\n  label = unique(c(edges_pv$from, edges_pv$to))\n) %>%\n  left_join(\n    bind_rows(\n      people_nodes %>% select(label, type = sub_type),\n      vessel_nodes %>% select(label, type = sub_type)\n    ),\n    by = \"label\"\n  ) %>%\n  mutate(\n    shape = ifelse(type == \"Person\", 16, 17), # \n    color = ifelse(type == \"Person\", \"#FF8888\", \"#44C6C6\")\n  ) %>%\n  select(id, label, type, shape, color)\n\nrelation_types <- sort(unique(edges_pv$relationship_type))\n\nif (length(relation_types) <= 8) {\n  relation_colors <- RColorBrewer::brewer.pal(length(relation_types), \"Dark2\")\n} else {\n  relation_colors <- colorRampPalette(RColorBrewer::brewer.pal(8, \"Dark2\"))(length(relation_types))\n}\nrelation_color_map <- setNames(relation_colors, relation_types)\n\nedges <- edges_pv %>%\n  mutate(\n    from = as.character(from),\n    to = as.character(to),\n    relationship = relationship_type,\n    color = relation_color_map[relationship_type]\n  ) %>%\n  select(from, to, relationship, color)\n```\n:::\n\n\n\n#### Step 5: Plot static network with node/edge legends\n\nUse ggraph to plot a static network diagram. Node types (person/vessel) have different shapes and colors, and the legend on the right automatically distinguishes them. Edge colors represent relationship types.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidygraph)\nlibrary(ggraph)\n\ngraph_pv <- tbl_graph(\n  nodes = nodes,\n  edges = edges %>% rename(label = relationship),\n  directed = TRUE\n)\n\nggraph(graph_pv, layout = 'fr') +\n  geom_edge_link(\n    aes(color = label),\n    arrow = arrow(length = unit(3, 'mm')),\n    end_cap = circle(3, 'mm'),\n    width = 1.4,\n    alpha = 0.85,\n    show.legend = TRUE\n  ) +\n  geom_node_point(\n    aes(shape = type, color = type),\n    size = 6,\n    show.legend = TRUE\n  ) +\n  geom_node_text(\n    aes(label = label),\n    repel = TRUE,\n    size = 3.8,\n    vjust = 1.5\n  ) +\n  scale_shape_manual(\n    values = c(\"Person\" = 16, \"Vessel\" = 17),\n    name = \"Node Type\"\n  ) +\n  scale_color_manual(\n    values = c(\"Person\" = \"#FF8888\", \"Vessel\" = \"#44C6C6\"),\n    name = \"Node Type\"\n  ) +\n  scale_edge_color_manual(\n    values = relation_color_map,\n    name = \"Relationship\"\n  ) +\n  guides(\n    edge_color = guide_legend(\n      override.aes = list(\n        linetype = 1,\n        size = 3 \n      )\n    )\n  ) +\n  theme_void() +\n  labs(title = \"People–Vessel Interaction Network\") +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(hjust = 0.5, size = 15, face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n### Task 2.2 ：Identify closely associated groups and the predominant topics for each group\n\n#### Step 1: Data preparation\n\nreferring to task 2.1 we already get - nodes: id, label, type - edges: from, to, relationship_type\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedges <- edges_pv %>%\n  mutate(\n    from = as.character(from),\n    to = as.character(to),\n    relationship_type = as.character(relationship_type)\n  ) %>%\n  select(from, to, relationship_type)\n\nedges <- edges %>%\n  mutate(title = relationship_type)\n```\n:::\n\n\n\n#### Step 2: Building un-directed graph\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_pv_undirected <- tbl_graph(\n  nodes = nodes,\n  edges = edges,\n  directed = FALSE\n)\n```\n:::\n\n\n\n#### Step 3:Louvain Community detection\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_pv_undirected <- graph_pv_undirected %>%\n  mutate(community = as.factor(group_louvain()))\n```\n:::\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}