project:
  type: website

website:
  title: "ISSS608-YL"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
          - href: "Hands-on_EX/Hands-On_Ex01/Hnds-on_EX01.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

