---
title: "Hands-on Exercise 5"
author: "Yang Lu"
date: "15 May 2025"
date-modified: "last-modified"
format: html
code-fold: true
code-summary: "Show the code"
editor: visual
execute: 
  eval: true  
  echo: true  
  warning: false 
  freeze: true 
---

# VAST Challenge 2025-Mini-Challenge 3

For the exercise, our group will choose MC 3 as our main topic, the detail background referring to \[VAST MC3\](<https://vast-challenge.github.io/2025/MC3.html>)

## 2.Setting up

2.1 loading packages

\[add the description about those packages\]

SmartEDA,

tidygraph,

ggraph

```{r}
pacman::p_load(
  jsonlite,
  tidyverse,
  SmartEDA,
  tidygraph,
  ggraph)
```

2.2 Loading data

```{r}
mc3_schema<- fromJSON("data/MC3_schema.json")
glimpse(mc3_schema)

```

```{r}
mc1_graph<- fromJSON("data/MC1_graph.json")
glimpse(mc1_graph)

```

```{r}
mc3_graph<- fromJSON("data/MC3_graph.json")
glimpse(mc3_graph)

```

inspect

the str() to using to overview the dataset, and getting the maximum data in whole dtaset.

```{r}

str(mc3_graph,max.level = 1)

```

```{r}
str(mc3_schema,max.level = 1)

```

```{r}
str(mc1_graph,max.level = 1)

```

```{r}
nodes_tbl < -as_tibble(mc3_schema$nodes)
edges_tbl < -as_tibble(mc3_$edges)

```

```{r}
nodes_tbl < -as_tibble(mc1_graph$nodes)
edges_tbl < -as_tibble(mc1_graph$edges)

```

